In [139]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [158]:
dataset = pd.read_csv('2010-capitalbikeshare-tripdata.csv')

In [159]:
dataset.head()

Duration           Start date             End date  Start station number  \
0      1012  2010-09-20 11:27:04  2010-09-20 11:43:56                 31208   
1        61  2010-09-20 11:41:22  2010-09-20 11:42:23                 31209   
2      2690  2010-09-20 12:05:37  2010-09-20 12:50:27                 31600   
3      1406  2010-09-20 12:06:05  2010-09-20 12:29:32                 31600   
4      1413  2010-09-20 12:10:43  2010-09-20 12:34:17                 31100   

                   Start station  End station number  \
0       M St & New Jersey Ave SE               31108   
1                 1st & N St  SE               31209   
2                  5th & K St NW               31100   
3                  5th & K St NW               31602   
4  19th St & Pennsylvania Ave NW               31201   

                     End station Bike number Member type  
0                  4th & M St SW      W00742      Member  
1                 1st & N St  SE      W00032      Member  
2  19th St & Pennsylvania Ave NW      W00993      Member  
3        Park Rd & Holmead Pl NW      W00344      Member  
4                 15th & P St NW      W00883      Member

In [160]:
dataset['Member type'].value_counts()

Member     91586
Casual     24001
Unknown       10
Name: Member type, dtype: int64

In [161]:
dataset.isnull().sum()

Duration                0
Start date              0
End date                0
Start station number    0
Start station           0
End station number      0
End station             0
Bike number             0
Member type             0
dtype: int64

In [162]:
dataset['Member type'].value_counts()

Member     91586
Casual     24001
Unknown       10
Name: Member type, dtype: int64

In [163]:
dataset.drop(dataset.index[dataset['Member type'] == 'Unknown'])

Duration           Start date             End date  \
0           1012  2010-09-20 11:27:04  2010-09-20 11:43:56   
1             61  2010-09-20 11:41:22  2010-09-20 11:42:23   
2           2690  2010-09-20 12:05:37  2010-09-20 12:50:27   
3           1406  2010-09-20 12:06:05  2010-09-20 12:29:32   
4           1413  2010-09-20 12:10:43  2010-09-20 12:34:17   
...          ...                  ...                  ...   
115592      2179  2010-12-31 23:20:32  2010-12-31 23:56:52   
115593       953  2010-12-31 23:21:57  2010-12-31 23:37:50   
115594       737  2010-12-31 23:27:28  2010-12-31 23:39:45   
115595       514  2010-12-31 23:37:38  2010-12-31 23:46:12   
115596     51962  2010-12-31 23:49:05  2011-01-01 14:15:08   

        Start station number                  Start station  \
0                      31208       M St & New Jersey Ave SE   
1                      31209                 1st & N St  SE   
2                      31600                  5th & K St NW   
3                      31600                  5th & K St NW   
4                      31100  19th St & Pennsylvania Ave NW   
...                      ...                            ...   
115592                 31110       20th St & Florida Ave NW   
115593                 31106       Calvert & Biltmore St NW   
115594                 31602        Park Rd & Holmead Pl NW   
115595                 31111                 10th & U St NW   
115596                 31111                 10th & U St NW   

        End station number                      End station Bike number  \
0                    31108                    4th & M St SW      W00742   
1                    31209                   1st & N St  SE      W00032   
2                    31100    19th St & Pennsylvania Ave NW      W00993   
3                    31602          Park Rd & Holmead Pl NW      W00344   
4                    31201                   15th & P St NW      W00883   
...                    ...                              ...         ...   
115592               31623  Columbus Circle / Union Station      W00859   
115593               31401           14th St & Spring Rd NW      W00914   
115594               31401           14th St & Spring Rd NW      W00973   
115595               31202                   14th & R St NW      W01119   
115596               31111                   10th & U St NW      W00771   

       Member type  
0           Member  
1           Member  
2           Member  
3           Member  
4           Member  
...            ...  
115592      Casual  
115593      Member  
115594      Member  
115595      Member  
115596      Casual  

[115587 rows x 9 columns]

In [164]:
dataset['Member type'].value_counts()

Member     91586
Casual     24001
Unknown       10
Name: Member type, dtype: int64

In [165]:
X = dataset.iloc[:,[0,3,5]].values
y = dataset.iloc[:,-1].values

In [166]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [167]:
print(y)

[1 1 1 ... 1 1 0]


In [168]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.25, random_state = 1)

In [169]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [170]:
print(X_train)

[[-0.16101204  0.7134468  -0.87054149]
 [-0.142986   -0.84850488 -0.30181428]
 [-0.06464206  1.88624328 -0.35010244]
 ...
 [-0.01957696 -0.27809932 -0.29108358]
 [-0.27540807 -0.86982845 -0.3661985 ]
 [-0.02858998 -0.84317399 -0.28035288]]


In [171]:
print(X_test)

[[ 0.15271039 -0.82718131  1.25950286]
 [-0.3332994  -1.37093241 -1.428538  ]
 [-0.18285129  1.7956181   1.24340681]
 ...
 [ 0.1495905   1.26252879 -0.23206472]
 [-0.12357334  0.18035749  0.19179801]
 [-0.25287552 -0.86449756 -0.3661985 ]]


In [172]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [173]:
y_pred = classifier.predict(X_test)

In [174]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 3249  2796     0]
 [ 3072 19778     1]
 [    1     3     0]]


0.7967820069204152

In [175]:
from sklearn.metrics import classification_report
classification_metrics = classification_report(y_test, y_pred)
print(classification_metrics)

              precision    recall  f1-score   support

           0       0.51      0.54      0.53      6045
           1       0.88      0.87      0.87     22851
           2       0.00      0.00      0.00         4

    accuracy                           0.80     28900
   macro avg       0.46      0.47      0.47     28900
weighted avg       0.80      0.80      0.80     28900

